.TH "gmameui" "6" "0.1" "Andrew Burton" "games"
.SH "NAME"
.LP 
gmameui \- GTK+ frontend for xmame
.SH "SYNTAX"
.LP 
gmameui
.SH "DESCRIPTION"
.LP 
GMAMEUI is a GTK+ based front end for MAME under Linux.
It allows you to create a game list using your current executable of xmame, 
display specific games (neo\-geo, CPS1/2, working, by version...), 
view the status of a game, change its preferences and launch it.
.SH "AUTHORS"
.LP 
Andrew Burton <adb@iinet.net.au>
Based heavily on GXMame
Stephane Pontier <shadow_walker@sourceforge.net>
.SH "REPORTING BUGS"
.LP
Report bugs in
.LP
http://sourceforge.net/tracker/?atid=1041607&group_id=217857
.SH "SEE ALSO"
.LP 
.BR xmame(6)
